### ISSUE TITLE
Getting error in basic REST Usage example

### ISSUE THREAD

**Issue by ghost** [osiset/basic_shopify_api#6]
I tried to run basic example: 

```
session = Session(domain="***.myshopify.com", key="shpat_********", secret="******")
opts = Options()
opts.version = "2022-04"
opts.mode = "public"
with Client(session, opts) as client:
    shop = client.rest("get", "/admin/api/shop.json", {"fields": "name,email"})
    print(shop.response)
    print(shop.body["name"])
```

but it gives below error:

```
Traceback (most recent call last):
  File "c:\PersonalData\Projects\ShopifyApp\myvenv\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\PersonalData\Projects\ShopifyApp\myvenv\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "c:\PersonalData\Projects\ShopifyApp\myvenv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
    merged_headers.update(headers)
  File "c:\PersonalData\Projects\ShopifyApp\myvenv\lib\site-packages\httpx\_models.py", line 198, in update
    headers = Headers(headers)
  File "c:\PersonalData\Projects\ShopifyApp\myvenv\lib\site-packages\httpx\_models.py", line 75, in __init__
    for k, v in headers.items()
  File "c:\PersonalData\Projects\ShopifyApp\myvenv\lib\site-packages\httpx\_models.py", line 75, in <listcomp>
    for k, v in headers.items()
  File "c:\PersonalData\Projects\ShopifyApp\myvenv\lib\site-packages\httpx\_utils.py", line 54, in normalize_header_value
    return value.encode(encoding or "ascii")
AttributeError: 'NoneType' object has no attribute 'encode'
```

Please let me know if I am missing anything here... Thanks..

**Comment by ghost** [comment]
Able to find my mistake after posting issue.

I was passing key instead of password for public app.
